### PR TITLE
fix: Refactor config files

### PR DESCRIPTION
**Pull request by allenhsieh**
Refactoring config files (DRY / simplify some logic)

### CODE REVIEW

**Comment by allenhsieh** [comment]
First round of moving things along hasn't seemed to broken anything yet
image
image

**Comment by allenhsieh** [comment]
@ButterB0wl I added you as a reviewer but this is still very much in draft

Going steady -- taking it piece by piece and making sure not to break tests/functionality: 
image

**Comment by allenhsieh** [comment]
```protected saveConfigToFile(
    objectToSave: ConfigPersist,
    saveLocation: string = ".oss-index-config"
  ): boolean {
    try {
      writeFileSync(
        this.getSaveLocation(saveLocation),
        safeDump(objectToSave, { skipInvalid: true })
      );
      return true;
    } catch (e) {
      throw new Error(e);
    }
  }

  public saveFile(config: ConfigPersist, flag: string): boolean {
    if (flag === "ossi") {
      return this.saveConfigToFile(config, ".oss-index-config");
    }
    return this.saveConfigToFile(config, '.iq-server-config');
  }```

These two are a bit redundant at this point -- convo for when Jeffry back:stick `saveFile` logic into `saveConfigToFile`?

**Comment by ButterB0wl** [comment]
yeah I would get rid of it.  In the old code it was just calling saveConfigFile from the parent so its unnecessary with a consolidated config file:

```
public saveFile(iqServerConfig: ConfigPersist): boolean {
    return super.saveConfigToFile(iqServerConfig, this.iqConfigFile);
  }
```

**Comment by allenhsieh** [comment]
@ButterB0wl haha artie! Take a look at alpha before you dive too deep, we made some changes to config to be able to allow used to select cache location

**Comment by ButterB0wl** [comment]
should we kill this?

**Comment by allenhsieh** [comment]
> should we kill this?

@ButterB0wl just saw this. yeah i'll kill this branch and PR right now

**Pull request closed without merging**
